In [1]:
import cv2
import sys

# Get user supplied values
# imagePath = sys.argv[1]
imagePath = 'images/kevin-happy.jpg'
cascPath = "haarcascade_frontalface_default.xml"

# Create the haar cascade
faceCascade = cv2.CascadeClassifier(cascPath)

# Read the image
image = cv2.imread(imagePath)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)


# Detect faces in the image
faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30),
)

print("Found {0} faces!".format(len(faces)))

# Draw a rectangle around the faces
for (x, y, w, h) in faces:
    print ('x, y =', (x, y))
    print ('w, h =', (w, h))
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
    print ('x+w = ', x+w)
    print ('y+h = ', y+h)
#     cv2.imwrite('images/kevin-happy-found.jpg', img[x:x+w, y:y+h])

cv2.imshow("img", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Found 1 faces!
x, y = (548, 293)
w, h = (197, 197)
x+w =  745
y+h =  490


In [2]:
x, y, w, h

(548, 293, 197, 197)

In [3]:
import cv2
img = cv2.imread('images/kevin-happy.jpg')
crop_img = img[y:y+h, x:x+w]
cv2.imwrite('images/kevin-happy-cropped.jpg', crop_img)
cv2.imshow("cropped", crop_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Convert sizes of images to 224x224

In [4]:
## Change all images to size None, 224, 224, 3 ##
from PIL import Image
import PIL
basewidth = 224
baseheight = 224
img = Image.open("images/kevin-happy-cropped.jpg")
img = img.resize((basewidth, baseheight), PIL.Image.ANTIALIAS)
img.save("images/kevin-happy-cropped.jpg")

# Feature Extraction

In [5]:
from keras.applications import vgg16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from keras.models import Model
import numpy as np
import matplotlib.pyplot as plt

img_path = "images/kevin-happy-cropped.jpg"
img = image.load_img(img_path, target_size=(224, 224))
model = vgg16.VGG16(weights='imagenet', include_top=True)
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)
features = model.predict(x)
model_extractfeatures = Model(input=model.input, output=model.get_layer('fc2').output)
fc2_features = model_extractfeatures.predict(x)
fc2_features = fc2_features.reshape((4096,1))

c:\users\kevin\anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


ValueError: Error when checking : expected input_1 to have shape (None, 224, 224, 3) but got array with shape (1, 48, 48, 3)

In [6]:
fc2_features.shape

(4096, 1)

In [4]:
import copy
happy = fc2_features.copy()
happy

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [14]:
fc2_features

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
cosine_similarity([fc2_features.reshape(-1)], [happy.reshape(-1)])

array([[0.8383744]], dtype=float32)

In [ ]:
## 0.6646794
## 0.98057544