In [1]:
import matplotlib.pyplot as plt
import numpy as np
import keras
import tensorflow as tf
import os
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.optimizers import Adadelta
from keras.utils import np_utils
# from keras.regularizers import l2, activity_l2
import numpy
import csv
import scipy.misc
import scipy
from scipy import ndimage
import numpy as np
from keras.preprocessing.image import ImageDataGenerator

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)

c:\users\kevin\anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [12]:
path = 'E:/GT/DeepLearning_Hackathon/images/all/fer2013'
data = pd.read_csv(path + '/fer2013.csv')

In [13]:
data.head()

emotion                                             pixels     Usage
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...  Training
1        0  151 150 147 155 148 133 111 140 170 174 182 15...  Training
2        2  231 212 156 164 174 138 161 173 182 200 106 38...  Training
3        4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...  Training
4        6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...  Training

In [14]:
mapping= {0:'Angry', 1:'Disgust', 2:'Fear', 3:'Happy', 4:'Sad', 5:'Surprise', 6:'Neutral'}

In [15]:
len(data.pixels[0].split(" "))

2304

In [16]:
new_pixels = []
for i in data.pixels.tolist():
    new_pixels.append(np.asarray([int(x) for x in i.split(" ")]).reshape((48,48,1)))
data.pixels = new_pixels
data.head()

emotion                                             pixels     Usage
0        0  [[[70], [80], [82], [72], [58], [58], [60], [6...  Training
1        0  [[[151], [150], [147], [155], [148], [133], [1...  Training
2        2  [[[231], [212], [156], [164], [174], [138], [1...  Training
3        4  [[[24], [32], [36], [30], [32], [23], [19], [2...  Training
4        6  [[[4], [0], [0], [0], [0], [0], [0], [0], [0],...  Training

In [17]:
from keras.layers import Activation, Convolution2D, Dropout, Conv2D
from keras.layers import AveragePooling2D, BatchNormalization
from keras.layers import GlobalAveragePooling2D
from keras.models import Sequential
from keras.layers import Flatten
from keras.models import Model
from keras.layers import Input
from keras.layers import MaxPooling2D
from keras.layers import SeparableConv2D
from keras import layers
from keras.regularizers import l2

In [18]:
def simple_CNN(input_shape, num_classes):

    model = Sequential()
    model.add(Convolution2D(filters=16, kernel_size=(7, 7), padding='same',
                            name='image_array', input_shape=input_shape))
    model.add(BatchNormalization())
    model.add(Convolution2D(filters=16, kernel_size=(7, 7), padding='same'))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(AveragePooling2D(pool_size=(2, 2), padding='same'))
    model.add(Dropout(.5))

    model.add(Convolution2D(filters=32, kernel_size=(5, 5), padding='same'))
    model.add(BatchNormalization())
    model.add(Convolution2D(filters=32, kernel_size=(5, 5), padding='same'))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(AveragePooling2D(pool_size=(2, 2), padding='same'))
    model.add(Dropout(.5))

    model.add(Convolution2D(filters=64, kernel_size=(3, 3), padding='same'))
    model.add(BatchNormalization())
    model.add(Convolution2D(filters=64, kernel_size=(3, 3), padding='same'))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(AveragePooling2D(pool_size=(2, 2), padding='same'))
    model.add(Dropout(.5))

    model.add(Convolution2D(filters=128, kernel_size=(3, 3), padding='same'))
    model.add(BatchNormalization())
    model.add(Convolution2D(filters=128, kernel_size=(3, 3), padding='same'))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(AveragePooling2D(pool_size=(2, 2), padding='same'))
    model.add(Dropout(.5))

    model.add(Convolution2D(filters=256, kernel_size=(3, 3), padding='same'))
    model.add(BatchNormalization())
    model.add(Convolution2D(
        filters=num_classes, kernel_size=(3, 3), padding='same'))
    model.add(GlobalAveragePooling2D())
    model.add(Activation('softmax', name='predictions'))
    return model

In [19]:
model = simple_CNN((48,48,1), 7)

In [20]:
from keras.utils import to_categorical
trainX = data.pixels[:int(0.8 * len(data.pixels))].tolist()
trainY = data.emotion[:int(0.8 * len(data.emotion))].tolist()

testX = data.pixels[int(0.8 * len(data.pixels)):].tolist()
testY = data.emotion[int(0.8 * len(data.emotion)):].tolist()

# type(trainX)
model.compile(optimizer='adam', loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(np.array(trainX), to_categorical(trainY), epochs=15)

Epoch 1/15
28709/28709 [==============================] - 28s 972us/step - loss: 1.8175 - acc: 0.2711
Epoch 2/15
28709/28709 [==============================] - 24s 852us/step - loss: 1.6077 - acc: 0.3686
Epoch 3/15
28709/28709 [==============================] - 24s 853us/step - loss: 1.5261 - acc: 0.4056
Epoch 4/15
28709/28709 [==============================] - 25s 855us/step - loss: 1.4651 - acc: 0.4286
Epoch 5/15
28709/28709 [==============================] - 25s 855us/step - loss: 1.4177 - acc: 0.4495
Epoch 6/15
28709/28709 [==============================] - 25s 857us/step - loss: 1.3890 - acc: 0.4658
Epoch 7/15
28709/28709 [==============================] - 25s 858us/step - loss: 1.3705 - acc: 0.4687
Epoch 8/15
28709/28709 [==============================] - 25s 856us/step - loss: 1.3514 - acc: 0.4790
Epoch 9/15
28709/28709 [==============================] - 25s 857us/step - loss: 1.3376 - acc: 0.4858
Epoch 10/15
28709/28709 [==============================] - 25s 857us/step - loss: 

# Save model and weights

In [21]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


# Capture images and classify

In [22]:
import cv2
import sys

# Get user supplied values
# imagePath = sys.argv[1]
imagePath = 'images/kevin-happy-new.jpg'
cascPath = "haarcascade_frontalface_default.xml"

# Create the haar cascade
faceCascade = cv2.CascadeClassifier(cascPath)

# Read the image
image = cv2.imread(imagePath)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)


# Detect faces in the image
faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30),
)

print("Found {0} faces!".format(len(faces)))

# Draw a rectangle around the faces
for (x, y, w, h) in faces:
    print ('x, y =', (x, y))
    print ('w, h =', (w, h))
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
    print ('x+w = ', x+w)
    print ('y+h = ', y+h)
#     cv2.imwrite('images/kevin-happy-found.jpg', img[x:x+w, y:y+h])

cv2.imshow("img", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Found 1 faces!
x, y = (472, 231)
w, h = (333, 333)
x+w =  805
y+h =  564


In [23]:
import cv2
img = cv2.imread('images/kevin-happy-new.jpg')
crop_img = img[y:y+h, x:x+w]
cv2.imwrite('images/kevin-happy-new-cropped.jpg', crop_img)
cv2.imshow("cropped", crop_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
import os
import cv2
import PIL

print (os.getcwd())
image = cv2.imread('images/kevin-happy-new-cropped.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
gray

E:\GT\DeepLearning_Hackathon


array([[152, 151, 149, ..., 111, 107, 106],
       [151, 150, 150, ..., 107, 103, 101],
       [150, 150, 149, ..., 105, 101,  99],
       ...,
       [ 45,  45,  44, ...,  64,  64,  65],
       [ 45,  45,  46, ...,  66,  66,  66],
       [ 44,  45,  46, ...,  66,  66,  67]], dtype=uint8)

In [25]:
cv2.imshow("img", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
from PIL import Image

img = cv2.resize(gray, (48, 48), PIL.Image.ANTIALIAS)

In [27]:
img.shape

(48, 48)

In [28]:
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
img

array([[146, 146, 144, ..., 114, 116, 109],
       [149, 144, 144, ..., 118, 115, 104],
       [145, 143, 142, ..., 115, 107, 111],
       ...,
       [ 42,  41,  40, ...,  56,  56,  58],
       [ 42,  41,  41, ...,  58,  63,  63],
       [ 44,  44,  47, ...,  62,  66,  63]], dtype=uint8)

In [35]:
preds = model.predict(img.reshape(1, 48, 48, 1))

In [36]:
preds

array([[7.36504188e-03, 1.12034024e-04, 5.67797618e-03, 7.92389691e-01,
        1.06053473e-02, 6.52102893e-03, 1.77328840e-01]], dtype=float32)

In [39]:
mapping

{0: 'Angry',
 1: 'Disgust',
 2: 'Fear',
 3: 'Happy',
 4: 'Sad',
 5: 'Surprise',
 6: 'Neutral'}

In [42]:
users_face = np.argmax(preds)

In [41]:
correct_answer = 3

In [43]:
preds[0][correct_answer] * 10

7.923896908760071